apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-radar
  labels:
    app: dependency-radar
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dependency-radar
  template:
    metadata:
      labels:
        app: dependency-radar
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dependency-radar
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.repos.hostPath }}
          volumeMounts:
            - name: repos
              mountPath: /repos
              readOnly: true
          {{- end }}
      {{- if .Values.repos.hostPath }}
      volumes:
        - name: repos
          hostPath:
            path: {{ .Values.repos.hostPath }}
            type: Directory
      {{- end }}
