apiVersion: v1
kind: Service
metadata:
  name: dependency-radar
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dependency-radar
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
