import type cytoscape from "cytoscape";

export const GRAPH_STYLE: cytoscape.StylesheetJson = [
  {
    selector: "node",
    style: {
      label: "data(label)",
      color: "#1b1f23",
      "font-size": 14,
      "min-zoomed-font-size": 7,
      "font-family": "Inter, Avenir Next, Trebuchet MS, Segoe UI, sans-serif",
      "text-valign": "bottom",
      "text-halign": "center",
      "text-margin-y": 7,
      "text-outline-width": 0,
      "background-color": "#cbd5e1",
      width: 30,
      height: 30,
      "border-width": 1.5,
      "border-color": "rgba(15, 23, 42, 0.22)",
    },
  },
  {
    selector: ".n-repo",
    style: {
      shape: "round-rectangle",
      "background-opacity": 0,
      "background-color": "#2563eb",
      "border-style": "dashed",
      "border-color": "#2563eb",
      "border-opacity": 0.45,
      "text-valign": "top",
      "text-halign": "left",
      "text-justification": "left",
      "font-size": 11,
      "font-weight": 700,
      "text-transform": "uppercase",
      "font-family": "Inter, Avenir Next, Trebuchet MS, Segoe UI, sans-serif",
      color: "#2563eb",
      padding: "36px",
      "text-margin-x": 18,
      "text-margin-y": 16,
      "text-max-width": "260px",
      "text-wrap": "wrap",
    },
  },
  { selector: ".n-project", style: { shape: "round-rectangle", "background-color": "#cbd5e1", width: 48, height: 32 } },
  { selector: ".kind-library", style: { "background-color": "#94a3b8" } },
  { selector: ".kind-test", style: { "background-color": "#8b5cf6" } },
  { selector: ".kind-web", style: { "background-color": "#f59e0b" } },
  { selector: ".kind-blazor", style: { "background-color": "#ec4899" } },
  { selector: ".kind-service", style: { "background-color": "#14b8a6" } },
  { selector: ".kind-nuget-producing", style: { "border-color": "#16a34a", "border-width": 3 } },
  { selector: ".n-package", style: { shape: "diamond", width: 30, height: 30 } },
  { selector: ".pkg-internal", style: { "background-color": "#16a34a", color: "#14532d" } },
  { selector: ".pkg-unknown", style: { "background-color": "#64748b", opacity: 0.92 } },
  { selector: ".pkg-external", style: { "background-color": "#64748b", opacity: 0.92 } },
  {
    selector: "edge",
    style: {
      width: 1.5,
      "line-color": "rgba(71, 85, 105, 0.26)",
      "target-arrow-shape": "triangle",
      "target-arrow-color": "rgba(71, 85, 105, 0.26)",
      "curve-style": "bezier",
      "arrow-scale": 0.85,
      "overlay-opacity": 0,
      "source-distance-from-node": 3,
      "target-distance-from-node": 5,
    },
  },
  { selector: ".e-projectRef", style: { width: 3, "line-color": "#0f766e", "target-arrow-color": "#0f766e", "target-arrow-shape": "triangle" } },
  { selector: ".e-packageRef", style: { width: 2.5, "line-color": "#dc2626", "target-arrow-color": "#dc2626", "target-arrow-shape": "vee" } },
  { selector: ".e-packageRefTransitive", style: { width: 2.2, "line-color": "#7c3aed", "target-arrow-color": "#7c3aed", "target-arrow-shape": "vee", "line-style": "dashed" } },
  { selector: ".e-producedBy", style: { width: 2.3, "line-color": "#16a34a", "target-arrow-color": "#16a34a", "target-arrow-shape": "triangle", "line-style": "dotted" } },
  {
    selector: ".n-repo:active",
    style: {
      "overlay-color": "#2563eb",
      "overlay-opacity": 0.07,
      "overlay-padding": 6,
    },
  },
  {
    selector: ".n-repo:hover",
    style: {
      "background-opacity": 0.11,
    },
  },
  { selector: ".is-filtered", style: { display: "none" } },
  { selector: ".dim", style: { opacity: 0.07 } },
  { selector: "edge.dim", style: { "target-arrow-shape": "none" } },
  { selector: ".hilite", style: { opacity: 1, "z-index": 20 } },
  {
    selector: ".ancestor",
    style: {
      "border-color": "#dc2626",
      "border-width": 6,
      "underlay-color": "rgba(220, 38, 38, 0.22)",
      "underlay-shape": "ellipse",
      "underlay-padding": 8,
    },
  },
  {
    selector: ".descendant",
    style: {
      "border-color": "#0f766e",
      "border-width": 6,
      "underlay-color": "rgba(15, 118, 110, 0.22)",
      "underlay-shape": "ellipse",
      "underlay-padding": 8,
    },
  },
  {
    selector: ":selected",
    style: {
      "border-color": "#2563eb",
      "border-width": 4,
      "overlay-opacity": 0,
    },
  },
];
